default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DATABASE_USER", ENV["USER"]) %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

test:
  <<: *default
  database: hookshot_test
